# Site settings
title: ~micah
email: micah@micahwalter.com
author: micah walter
description: "I'm on tilde club."
baseurl: "http://tilde.club/~micah"
url: "http://tilde.club/~micah"
google_analytics:
animated: false
show_related_posts: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass:
  compressed: true
